(()=>{console.log("FB AIO: Web timer ENABLED"),x();function T(s,r,i=1e3){return new Promise(u=>{let l=Math.random().toString(36),g="aio-contentscript-sendto-pagescript"+l,d=null,p=w=>{d&&window.clearTimeout(d),window.removeEventListener(g,c),u(w)},c=w=>p(w.detail?.data);i>0&&(d=window.setTimeout(()=>p(null),i)),window.addEventListener(g,c,{once:!0}),window.dispatchEvent(new CustomEvent("aio-pagescript-sendto-contentscript",{detail:{event:s,data:r,uuid:l}}))})}function f(s,r,i=1e3){return T("aio-runInBackground",{fnPath:s,params:r},i)}async function x(){typeof window.fbaio_web_timer_cleanup=="function"&&window.fbaio_web_timer_cleanup();let s=window===window.top,r=[];function i(e,t,n,o){e.addEventListener(t,n,o),r.push(()=>e.removeEventListener(t,n))}window.fbaio_web_timer_cleanup=()=>{typeof h=="function"&&h(),r.forEach(e=>e())};let u=!0,l=E(function(e,t){u=!0},1e3/24),g=["pointerover","pointerenter","pointerdown","pointermove","pointerup","pointerleave","click","contextmenu","touchstart","touchmove","touchend","keydown","keyup","keypress","wheel","scroll","blur","focus"],d="fbaio_web_timer_updateLastActive",p="fbaio-web-timer-overlay";g.forEach(e=>{s?i(window,e,t=>{t.target?.id!=p&&l?.(e,!0)}):i(window,e,E(t=>{window.top.postMessage({type:d,event:e},"*")},1e3/24))});let c="fbaio_web_timer_checkFocus";if(s||i(window,"message",e=>{e.data?.type===c&&window.top.postMessage({type:c+"result",uuid:e.data?.uuid,focused:document.hasFocus()},"*")}),!s)return;i(window,"message",e=>{e.data?.type===d&&l(e.data?.event,!1)},!1),i(document,"visibilitychange",()=>{document.hidden||l()});let w=1,F=10,I=60,q=10,B=!0,b="\u200B",M=0,_=0,L=0,y=0;k().then(e=>{_=e.value});let m=document.createElement("div");m.id=p,m.style.cssText=`
            position: fixed;
            top: -100vh;
            left: 0;
            width: 100vw;
            height: 100vh;
            background-color: rgba(0, 0, 0, 0.35);
            z-index: 2147483646;
            transition: top 0.5s ease;
          `,["mousemove","click","touchstart"].forEach(e=>{i(m,e,l)});function S(e){e?(document.body.contains(m),m.style.top="0"):m.style.top="-100vh"}let D=setInterval(async()=>{u&&(M=performance.now(),u=!1);let e=await j();e.isIdle?B&&!document.hidden&&S(!0):S(!1),!document.hidden&&!e.isIdle&&(y++,L=_+y,A());let t=new Date;(t.getHours()===23&&t.getMinutes()===59&&t.getSeconds()===59||t.getHours()===0&&t.getMinutes()===0&&t.getSeconds()===0)&&h()},w*1e3);r.push(()=>{clearInterval(D),setTimeout(()=>A(!0),w*1e3)});let P=setInterval(()=>{h()},F*1e3);r.push(()=>clearInterval(P)),i(window,"beforeunload",h);function H(){if(document.hasFocus())return!0;let e=Array.from(document.querySelectorAll("iframe"));return e.length?new Promise(t=>{let n=Math.random().toString(36);setTimeout(()=>{window.removeEventListener("message",a),t(!1)},500),e.forEach(v=>{v.contentWindow.postMessage({type:c,uuid:n},"*")}),i(window,"message",a);let o=0;function a(v){v.data?.type===c+"result"&&v.data?.uuid===n&&(v.data?.focused===!0&&(window.removeEventListener("message",a),t(!0)),o++,o>=e.length&&(window.removeEventListener("message",a),t(!1)))}}):!1}async function j(){let e=await H()?I:q,t=~~(performance.now()-M);if(t<e*1e3)return{isIdle:!1,reason:"not enough time passed since last active "+t};let n=document.querySelectorAll("video, audio");for(let a of n)if(a.duration>0&&!a.paused)return{isIdle:!1,reason:"video / audio playing"};if((await f("chrome.tabs.query",[{active:!0,audible:!0,url:location.href}],300))?.length>0)return{isIdle:!1,reason:"this tab is audible "};let o=Math.max(15,I);return await f("chrome.idle.queryState",[o],500)!="active"?{isIdle:!0,reason:"no system events in "+o+" secs"}:{isIdle:!0,reason:"no active events in "+e+" secs"}}async function h(){let{web_timer:e,host:t,today:n,value:o}=await k(),a=o+y;e[n][t]=a,_=a,y=0,await f("chrome.storage.local.set",[{web_timer:e}])}async function k(){let e=location.hostname||location.pathname?.split("/")?.at(-1)||location.href,t=C(),n=(await f("chrome.storage.local.get",[["web_timer"]]))?.web_timer;typeof n!="object"&&(n={}),typeof n[t]!="object"&&(n[t]={}),n[t][e]||(n[t][e]=0);let o=Math.floor(n[t][e]);return{web_timer:n,host:e,today:t,value:o}}function C(){return N(new Date)}function N(e){let t=e.getFullYear(),n=$(e.getMonth()+1),o=$(e.getDate());return`${t}-${n}-${o}`}function $(e){return e.toString().padStart(2,"0")}function O(e){let t=Math.floor(e/3600),n=Math.floor((e-t*3600)/60),o=e-t*3600-n*60;return t==0?t="":t=`${t}:`,t==0&&n==0?n="":n=`${n}:`,t==0&&n==0&&o==0&&(o=""),`${t}${n}${o}`}async function A(e){let t=O(L)+" "+b,n=document.title;n.includes(b)&&(n=n.split(b)[1]);let o="web_timer_show_time_on_title";if((await f("chrome.storage.local.get",[[o]]))?.[o]){let a=e?n:t+n;document.title=a}else document.title=n}}function E(s,r){let i=null;return(...u)=>{i===null&&(s(...u),i=setTimeout(()=>{i=null},r))}}})();
